version: '3'
services:
  todo-mysql:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 5432:5432
    working_dir: /var/lib/mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=demo_xrzqx_todo
      - MYSQL_TCP_PORT=5432
    expose:
      - 5432
  todo-backend:
    build: ./backend
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - DB_USER=root
      - DB_PASSWORD=rahasia
      - DB_HOST=todo-mysql
      - DB_PORT=5432
      - DB_DATABASE=demo_xrzqx_todo
    depends_on:
      - todo-mysql
      - todo-frontend
  todo-frontend:
    build: ./frontend
    ports:
      - 8081:8080