-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 08:09:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demo_xrzqx_todo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo_xrzqx_todo` ;

-- -----------------------------------------------------
-- Schema demo_xrzqx_todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_xrzqx_todo` DEFAULT CHARACTER SET utf8 ;
USE `demo_xrzqx_todo` ;

-- -----------------------------------------------------
-- Table `demo_xrzqx_todo`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_xrzqx_todo`.`todo` ;

CREATE TABLE IF NOT EXISTS `demo_xrzqx_todo`.`todo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOTE` TEXT NOT NULL,
  `DONE` BIT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
